name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  check-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing tags
      packages: write  # Allow publishing packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Need previous commit to check version change
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if version changed
        id: version-check
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"

          # Get previous version from previous commit
          git checkout HEAD~1 package.json
          PREVIOUS_VERSION=$(node -p "require('./package.json').version")
          git checkout HEAD package.json
          echo "Previous version: $PREVIOUS_VERSION"

          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        if: steps.version-check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        if: steps.version-check.outputs.changed == 'true'
        run: npm ci

      - name: Build package
        if: steps.version-check.outputs.changed == 'true'
        run: npm run build

      - name: Run tests
        if: steps.version-check.outputs.changed == 'true'
        run: npm test
        continue-on-error: true  # Tests are optional for now

      - name: Publish to npm
        if: steps.version-check.outputs.changed == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create git tag
        if: steps.version-check.outputs.changed == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v${{ steps.version-check.outputs.version }}" -m "Release v${{ steps.version-check.outputs.version }}"
          git push origin "v${{ steps.version-check.outputs.version }}"

      - name: Create success comment
        if: steps.version-check.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const version = '${{ steps.version-check.outputs.version }}';
            const packageName = '@hexaust/teamcity-mcp';

            // Find the commit that triggered this workflow
            const { data: commit } = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            });

            // Create a comment on the commit
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: `✅ Successfully published **${packageName}@${version}** to npm!\n\n📦 View on npm: https://www.npmjs.com/package/${packageName}/v/${version}\n\nInstall with:\n\`\`\`bash\nnpx ${packageName}\n# or\nnpm install -g ${packageName}\n\`\`\``
            });